[Icon Theme]
Name=Uneri-Light
Comment=Uneri icon set
Inherits=Adwaita,hicolor
Example=folder

Directories=scalable/places,scalable/actions,scalable/devices,scalable/mimetypes,scalable/status,symbolic/actions,symbolic/status

[scalable/places]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/actions]
Size=24
MinSize=16
MaxSize=512
Type=Scalable
Context=Actions

[scalable/devices]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[scalable/mimetypes]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[scalable/status]
Size=24
MinSize=16
MaxSize=512
Type=Scalable
Context=Status

[symbolic/actions]
Size=16
MinSize=8
MaxSize=512
Type=Scalable
Context=Actions

[symbolic/status]
Size=16
MinSize=8
MaxSize=512
Type=Scalable
Context=Status
